server:
  port: 10020


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: coderliu-generate
  datasource:
    username: root
    password: Coderliu123456!
    url: jdbc:mysql://localhost/coderliu-generate?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      auto-commit: true
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    connect-timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  # \u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D(since 3.3.0,\u914D\u7F6E\u540E\u53EF\u4EE5\u5FFD\u7565\u4E0D\u914D\u7F6E\u6B65\u9AA42)
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
    banner: false

#feign\u5168\u5C40\u914D\u7F6E
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

##\u52A0\u5BC6\u7EC4\u4EF6\u9700\u8981
#jasypt:
#  encryptor:
#    password: coderliu

