server:
  port: 10100


spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: coderliu-fileserver
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/coderliu_server?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      auto-commit: true
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
      location: /data/tmp
#feign全局配置
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50


minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: admin123
  bucketName: coderliu-fileserver
