server:
  port: 10100


spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.128:8848
  application:
    name: coderliu-fileserver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
#feign全局配置
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50



