server:
  port: 10100


spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: coderliu-fileserver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
      location: /data/tmp
#feign全局配置
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50


minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: admin123
  bucketName: coderliu-fileserver
