server:
  port: 10030


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: coderliu-auth
  datasource:
    username: root
    password: Coderliu123456!
    url: jdbc:mysql://localhost:3306/coderliu_admin?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    connect-timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
#feign全局配置
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    org.springframework.security: debug
#    org.springframework.security.oauth2: debug
