server:
  port: 10030


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.130:8848
  application:
    name: coderliu-auth

#feign全局配置
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
