server:
  port: 10020
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.128:8848
    gateway:
      routes:
        - id: auth
          uri: lb://coderliu-auth
          predicates:
            - Path=/coderliu-auth/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
  application:
    name: coderliu-gateway


management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  endpoint:
    health:
      show-details: always


